#!/bin/sh
# TODO: eventually rewrite in Python to support Windows
SKELDIR=`dirname $(readlink $0)`
WORKDIR="`pwd`"

list_languages() {
	(
	 cd ${SKELDIR} || exit 1
	 ls -F|grep / | awk -F - '{print $4}'|sed -e 's,/,,'|sort -u
	)
}

list_templates() {
	(
	 cd ${SKELDIR} || exit 1
	 ls -F | grep /$ | sed -e 's,/,,'
	)
}

case "$1" in
"-l"|list)
	list_templates
	;;
"-L"|langs)
	list_languages
	;;
"-h"|"")
	echo "r2skel [-lL] | [template] [new-directory]"
	echo "Options:"
	echo " -l - list all the available project templates"
	echo " -L - list all the languages"
	echo "Templates: "
	list_templates | xargs -L1 echo ' -'
	;;
*)
	if [ -n "$2" ]; then
		SD="${SKELDIR}/$1"
		if [ ! -d "${SD}" ]; then
			echo "Invalid skeleton name. See 'r2skel -l'"
			exit 1
		fi
		if [ -d "${2}" ]; then
			echo "Target directory already exists"
			exit 1
		fi
		cp -rf "${SD}" "$2"
	else
		echo "Usage: r2skel [template] [new-directory]"
	fi
	;;
esac

